name: Bug Report Form
description: File a bug Report for our Godot Strategies-V1
title: "Found a [bug] in [section name]"
labels: ["bug","development"]
assignees:
  - Tilliforkids
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen and what went wrong?
    placeholder: Tell us what you see! Suggestions are welcome
  validations:
    required: true
- type: dropdown
  id: pages
  attributes:
    label: Which section in Godot Strategies-V1 did you face the issue?
    multiple: true
    options:
      - Yoga
      - Bubble Pop
      - Rainbow Breathing
      - Water Drinking
      - Colouring
      - Self Hug
  validations:
    required: true
- type: textarea
  id: reprod
  attributes:
    label: "Reproduction steps"
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    render: bash
  validations:
    required: true
- type: textarea
  id: screenshot
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    value: |
      ![DESCRIPTION](LINK.png)
    render: bash
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: bash
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: Browsers
    description: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
      - Opera
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: OS
    description: What is the impacted environment ?
    multiple: true
    options:
      - Windows
      - Linux
      - Mac
  validations:
    required: false
- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: "High Priority= must be completed as soon possible, Medium Priority= need to be completed but can wait after high priority items, Low Priority= \"nice to have\" changes."
    multiple: false
    options:
      - High Priority
      - Medium Priority
      - Low Priority
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://tillioss.github.io/docs/code-of-conduct)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
