name: Feedback/Doubts Form
description: Suggest feedback or ask doubts for more clarity with regard to our Godot Strategies
title: "Have a [feedback], [doubt]"
labels: ["feedback/doubt","documentation"]
assignees:
  - Tilliforkids
  - Briandsouza-17
  - Hannah31George
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What is your Feedback/ Doubt?
    description: Kindly elaborate the same or what did you expect to happen or what went wrong,  and how can we improve?
    placeholder: Tell us what you’d like to know or see. Suggestions are welcome
  validations:
    required: true
- type: dropdown
  id: pages
  attributes:
    label: Which section in Godot Strategies-V1 do you want to suggest feedback or clarify doubts for?
    multiple: true
    options:
      - Yoga
      - Bubble Pop
      - Rainbow Breathing
      - Water Drinking
      - Colouring
      - Self Hug
- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: "High Priority= must be completed as soon possible, Medium Priority= need to be completed but can wait after high priority items, Low Priority= \"nice to have\" changes."
    multiple: false
    options:
      - High Priority
      - Medium Priority
      - Low Priority
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://tillioss.github.io/docs/code-of-conduct)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
